title: "SimpleMfa"
remote_theme: just-the-docs/just-the-docs
search_enabled: false
baseurl: /simple-mfa
permalink: pretty
color_scheme: simple-mfa
aux_links:
  "GitHub": https://github.com/vikaspotluri123/simple-mfa
aux_links_new_tab: true
last_edit_timestamp: true
last_edit_timestamp_format: "%b %e %Y"
gh_edit_link: true
gh_edit_link_text: Suggest changes to this page on GitHub
gh_edit_repository: https://github.com/vikaspotluri123/simple-mfa
gh_edit_view_mode: tree
gh_edit_branch: master
gh_edit_source: docs
plugins:
 - jekyll-seo-tag
 - jekyll-mermaid
kramdown:
  syntax_highlighter: rouge
  input: GFM
mermaid:
  version: 'latest'

# Things you can enable when working locally
# theme: just-the-docs
