name: CI

on:
  push:
    branches:
      - main
      - renovate/*
  pull_request:
    branches:
      '*'

env:
  FORCE_COLOR: 3

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v3
      with:
        node-version: lts/*
        cache: yarn
      env:
        FORCE_COLOR: 0
    - name: Link Example App
      run: |
        yarn link
        cd example
        yarn link @potluri/simple-mfa
    - name: Install Dependencies
      run: |
        yarn install --frozen-lockfile --prefer-offline
        cd example
        yarn install --frozen-lockfile --prefer-offline
    - name: Build
      run: yarn pretest:coverage
    - name: Lint
      run: yarn lint
    - name: Test
      run: yarn test:coverage:ci
