name: Release
on:
  push:
    tags:
      - "*"
permissions:
  contents: write # Required to support publishing a release
jobs:
  automate:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      YARN_AUTH_TOKEN: ${{ secrets.NPM_RELEASE_TOKEN }}
      FORCE_COLOR: 1
    steps:
      - uses: gradebook/actions/actions/setup@master
        with:
          git-fetch-depth: 5
      - run: yarn install --frozen-lockfile --prefer-offline
      - run: yarn release-utils test-and-publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
